---
title: "Ejemplos de Tidyverse"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preparativos

## Carga de paquetes

```{r librerias, message = FALSE}
#dplyr
library(dplyr)
## ggplot2

library(ggplot2)
```


## Carga de datos

```{r carga-datos}
# Carga de datos desde un archivo CSV
rios <-
  read.csv(file = 'https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/hidrologia/fdc/fdc.csv')
```


```{r carga-datos-covid}
# Carga de datos desde un archivo CSV 
covid <- 
  read.csv(
    file='https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/datos/minsalud/covid/ultimafecha_CSV_GENERAL.csv', 
    sep = ","
  )
```
## dplyr

### mutate()
```{r}
# Despliegue de la estructura del data frame
str(rios)
```

```{r despliegue}
# Despliegue de los primeros de observaciones
slice_head(rios, n = 10)


# Despliegue de los ultimos de observaciones
slice_tail(rios, n=10)

# Despliege de una muestra aletoria de observaciones
slice_sample(rios, n=10)
```
```{r funciones enlazadas}
## funciones enlazadas
rios %>% slice_head(n = 10) %>% slice_tail(n = 2)
```

```{r funciones anidadas }
## funciones anidadas 
slice_tail(slice_head(rios, n = 10), n = 2)
```


```{r ejemplos mutate}
# Cambio de nombre de las columnas mediante rename()
rios <-
  rios %>%
  rename(fecha = Tiempo,
         pandora = Pandora.mm..637km2.,
         banano = Banano.mm..90km2.) %>% 
  mutate(fecha = as.Date(fecha, format = "%m/%d/%Y"),
         promedio = (pandora + banano) / 2)

slice_head(rios, n = 10)
```

```{r rios-histograma}
#Histograma simple
rios %>%
ggplot(aes(x = pandora))+
  geom_histogram()

```

```{r rios-histograma-opciones}
#histograma con opciones
rios %>%
  ggplot(aes(x = pandora))+
  geom_histogram(binwidth = 1,
                 color = "black",
                 fill = "white")

```

```{r rios-lineas}
#grafico de lineas simples
rios %>%
  ggplot(aes(x= fecha, y = pandora))+
  geom_line()

```


### Select()

```{r ejemplos-select}
# Selección, renombramiento y conversión de columnas
covid_columnas_seleccionadas <-
  covid %>%
  select(FECHA, muj_posi, hom_posi) %>%
  rename(
    fecha = FECHA,
    positivos_mujeres = muj_posi,
    positivos_hombres = hom_posi
  ) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))

slice_head(covid_columnas_seleccionadas, n = 10)
```

### Filter()

```{r emjemplos-filter}
# Selección, renombramiento, conversión de columnas y filtrado
covid_filtrado <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 3000)

slice_head(covid_filtrado, n = 20)
```

### arrange ()

```{r ejemplos-arrange}
# Selección, renombramiento, filtrado y conversión de columnas
covid_filtrado_ordenado_x_positivos_nuevos <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  filter(positivos_nuevos >= 2500) %>%
  arrange(desc(positivos_nuevos))

slice_head(covid_filtrado_ordenado_x_positivos_nuevos, n = 30)
```

## summarize()

```{r ejemplos-summarize-02}
# Selección, renombramiento, filtrado y conversión de columnas
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(anio = format(fecha,"%Y"), mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

covid_positivos_nuevos_sumarizado_x_mes

```
```{r ejemplos-summarize-01}
# Sumarizacion de casos nueves por mes 
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = sum(positivos_nuevos))

covid_positivos_nuevos_sumarizado_x_mes
```

```{r ejemplos-summarize-03}
# Promedio de casos por mes
covid_positivos_nuevos_sumarizado_x_mes <-
  covid %>%
  select(FECHA, nue_posi) %>%
  rename(fecha = FECHA, positivos_nuevos = nue_posi) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y")) %>%
  group_by(mes = format(fecha,"%m")) %>%
  summarise(suma_positivos = mean(positivos_nuevos))

covid_positivos_nuevos_sumarizado_x_mes
```

